name: Typing Tests

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  run:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false

    defaults:
      run:
        shell: bash

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    - name: Run mypy
      run: |
        python -m pip install -r requirements_typing.txt
        git clone https://github.com/progressivis/progressivis.git
        cd progressivis
        git submodule init
        git submodule update --remote --merge
        cd ..
        python -m pip install ./progressivis
        mv mypy_ci.ini mypy.ini
        mypy --strict ipyprogressivis/
