name: Typing Tests

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  run:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false

    defaults:
      run:
        shell: bash

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.13
      uses: actions/setup-python@v4
      with:
        python-version: '3.13'
    - name: Run mypy
      run: |
        git clone https://github.com/progressivis/progressivis.git
        python -m pip install progressivis[typing]@./progressivis
        mv mypy_ci.ini mypy.ini
        mypy --strict ipyprogressivis/
